# Generated by Django 4.0.5 on 2022-06-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('comment', models.TextField(max_length=1000, verbose_name='Отзыв')),
                ('avka', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Фото')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='Personal_predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_personal', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Личное предназначение')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('predictions_personal', models.TextField(max_length=3000, verbose_name='Личное предназначение текст')),
            ],
            options={
                'verbose_name': 'Личное предназначение',
                'verbose_name_plural': 'Личные предназначения',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1000, verbose_name='Услуги')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Social_predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_purpose', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Социальное предназначение')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('predictions_social', models.TextField(max_length=3000, verbose_name='Социальное предназначение текст')),
            ],
            options={
                'verbose_name': 'Социальное предназначение',
                'verbose_name_plural': 'Социальные предназначения',
            },
        ),
        migrations.CreateModel(
            name='Spiritual_predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spiritual_purpose', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Духовное предназначение')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('predictions_spiritual', models.TextField(max_length=3000, verbose_name='Духовное предназначение текст')),
            ],
            options={
                'verbose_name': 'Духовное предназначение',
                'verbose_name_plural': 'Духовные предназначения',
            },
        ),
    ]
