# Generated by Django 4.0.5 on 2022-06-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born_date', models.CharField(max_length=20, verbose_name='Дата рождения')),
                ('social_predictions', models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Социальное предназначение')),
                ('spiritual_predictions', models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Духовное предназначение')),
                ('personal_predictions', models.DecimalField(decimal_places=0, default=0, max_digits=50, verbose_name='Личное предназначение')),
            ],
            options={
                'verbose_name': 'Калькулятор пользователя',
                'verbose_name_plural': 'Калькуляторы пользователей',
            },
        ),
    ]
