# Generated by Django 4.0.5 on 2022-10-02 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_uset_created_uset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uset',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uset',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
