# Generated by Django 4.0.5 on 2022-10-02 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_alter_uset_created_alter_uset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uset',
            name='created',
        ),
        migrations.AddField(
            model_name='uset',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
