# Generated by Django 4.1.2 on 2022-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_remove_uset_created_uset_date_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=1000, verbose_name='Услуги')),
                ('like_view', models.CharField(default=' ', max_length=100, verbose_name='как выглядит')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='uset',
            name='name',
            field=models.CharField(default='someuser', max_length=50, verbose_name='Имя'),
        ),
    ]
