# Generated by Django 4.1.2 on 2023-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0006_service_rename_comments_comment_delete_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_uk',
            field=models.TextField(max_length=1000, null=True, verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='header_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='header_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='predictions_personal_en',
            field=models.TextField(max_length=3000, null=True, verbose_name='Личное предназначение текст'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='predictions_personal_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Личное предназначение текст'),
        ),
        migrations.AddField(
            model_name='personal_predictions',
            name='predictions_personal_uk',
            field=models.TextField(max_length=3000, null=True, verbose_name='Личное предназначение текст'),
        ),
        migrations.AddField(
            model_name='service',
            name='header_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='header_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='service',
            name='like_view_en',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='как выглядит'),
        ),
        migrations.AddField(
            model_name='service',
            name='like_view_ru',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='как выглядит'),
        ),
        migrations.AddField(
            model_name='service',
            name='like_view_uk',
            field=models.CharField(default=' ', max_length=100, null=True, verbose_name='как выглядит'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_en',
            field=models.TextField(max_length=1000, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_ru',
            field=models.TextField(max_length=1000, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='text_uk',
            field=models.TextField(max_length=1000, null=True, verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='header_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='header_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='predictions_social_en',
            field=models.TextField(max_length=3000, null=True, verbose_name='Социальное предназначение текст'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='predictions_social_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Социальное предназначение текст'),
        ),
        migrations.AddField(
            model_name='social_predictions',
            name='predictions_social_uk',
            field=models.TextField(max_length=3000, null=True, verbose_name='Социальное предназначение текст'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='header_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='header_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='predictions_spiritual_en',
            field=models.TextField(max_length=3000, null=True, verbose_name='Духовное предназначение текст'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='predictions_spiritual_ru',
            field=models.TextField(max_length=3000, null=True, verbose_name='Духовное предназначение текст'),
        ),
        migrations.AddField(
            model_name='spiritual_predictions',
            name='predictions_spiritual_uk',
            field=models.TextField(max_length=3000, null=True, verbose_name='Духовное предназначение текст'),
        ),
    ]
